from fastapi import APIRouter, Depends, HTTPException, Query, Body
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional, Dict, Any
import os
from app.database.session import get_db
from app.models.db_models import XRayCase, AIPrediction, ClinicalReview, User, Patient
try:
    from ml.inference.classifier import EfficientNetFractureClassifier
except ImportError:
    from app.ml.inference.classifier import EfficientNetFractureClassifier
from app.auth.security import get_current_user

router = APIRouter(prefix="/api/ai", tags=["AI Prediction & Grad-CAM"])

classifier = EfficientNetFractureClassifier(model_path="models/best_efficientnet_b0.pth")

class PredictRequest(BaseModel):
    case_id: str
    demo_mode: Optional[bool] = True

@router.post("/predict")
def run_ai_prediction(
    payload: Optional[PredictRequest] = Body(None),
    case_id: Optional[str] = Query(None),
    demo_mode: Optional[bool] = Query(True),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    target_id = (payload.case_id if payload else None) or case_id
    is_demo = payload.demo_mode if (payload and payload.demo_mode is not None) else (demo_mode if demo_mode is not None else True)

    if not target_id:
        raise HTTPException(status_code=400, detail="case_id parameter is required")

    case = db.query(XRayCase).filter(XRayCase.case_id == target_id).first()
    if not case:
        raise HTTPException(status_code=404, detail="X-ray case not found")

    quality_score = case.image_quality_score or 90.0
    quality_status = case.image_quality_status or ("ACCEPTABLE" if quality_score >= 50.0 else "POOR IMAGE QUALITY")

    if quality_score < 50.0 or quality_status == "POOR IMAGE QUALITY":
        prediction_data = {
            "case_id": target_id,
            "prediction": "Poor Image Quality",
            "fracture_probability": 0.0,
            "confidence": 0.0,
            "image_quality_score": quality_score,
            "image_quality_status": "POOR IMAGE QUALITY",
            "priority": "GRAY",
            "model": "EfficientNet-B0",
            "model_version": "v1.0",
            "demo_mode": is_demo,
            "demo_notice": "DEMO PREDICTION — NOT GENERATED BY THE TRAINED CLINICAL MODEL." if is_demo else None,
            "gradcam_path": None,
            "gradcam_available": False,
            "clinical_review_required": True,
            "disclaimer": "AI-assisted screening only. Final interpretation and clinical decision must be made by a qualified healthcare professional."
        }
    else:
        try:
            prediction_data = classifier.predict(
                case_id=case.case_id,
                image_path=case.image_path,
                enhanced_image_path=case.enhanced_image_path,
                image_quality_score=quality_score,
                demo_mode=is_demo
            )
            prediction_data["demo_mode"] = is_demo
            prediction_data["demo_notice"] = "DEMO PREDICTION — NOT GENERATED BY THE TRAINED CLINICAL MODEL." if is_demo else None
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"AI screening pipeline execution failed: {str(e)}")

    # Save or update AI prediction record in database
    prediction_record = db.query(AIPrediction).filter(AIPrediction.case_id == target_id).first()
    if not prediction_record:
        prediction_record = AIPrediction(
            case_id=target_id,
            model_name=prediction_data["model"],
            model_version=prediction_data["model_version"],
            prediction=prediction_data["prediction"],
            fracture_probability=prediction_data["fracture_probability"],
            confidence=prediction_data["confidence"],
            priority=prediction_data["priority"],
            gradcam_path=prediction_data.get("gradcam_path")
        )
        db.add(prediction_record)
    else:
        prediction_record.model_name = prediction_data["model"]
        prediction_record.model_version = prediction_data["model_version"]
        prediction_record.prediction = prediction_data["prediction"]
        prediction_record.fracture_probability = prediction_data["fracture_probability"]
        prediction_record.confidence = prediction_data["confidence"]
        prediction_record.priority = prediction_data["priority"]
        prediction_record.gradcam_path = prediction_data.get("gradcam_path")

    # Ensure clinical review entry is initialized as PENDING
    review = db.query(ClinicalReview).filter(ClinicalReview.case_id == target_id).first()
    if not review:
        review = ClinicalReview(
            case_id=target_id,
            reviewer_id=current_user.id,
            review_status="PENDING",
            reviewer_notes=""
        )
        db.add(review)

    db.commit()

    return prediction_data

@router.get("/result/{case_id}")
def get_ai_result(case_id: str, db: Session = Depends(get_db)):
    pred = db.query(AIPrediction).filter(AIPrediction.case_id == case_id).order_by(AIPrediction.created_at.desc()).first()
    case = db.query(XRayCase).filter(XRayCase.case_id == case_id).first()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")

    patient = db.query(Patient).filter(Patient.patient_id == case.patient_id).first()

    if not pred:
        # Auto-run prediction if not already computed
        prediction_data = classifier.predict(case_id, case.image_path, case.enhanced_image_path, case.image_quality_score or 90.0, demo_mode=True)
        prediction_data["demo_mode"] = True
        prediction_data["demo_notice"] = "DEMO PREDICTION — NOT GENERATED BY THE TRAINED CLINICAL MODEL."
        return prediction_data
    
    is_demo = getattr(pred, "demo_mode", True)

    return {
        "case_id": pred.case_id,
        "patient": {
            "patient_id": patient.patient_id if patient else case.patient_id,
            "name": patient.name if patient else "Unknown",
            "age": patient.age if patient else 0,
            "gender": patient.gender if patient else "Unspecified",
            "hospital_name": patient.hospital_name if patient else "Regional Clinic"
        },
        "case": {
            "case_id": case.case_id,
            "body_region": case.body_region,
            "image_quality_score": case.image_quality_score,
            "image_quality_status": case.image_quality_status,
            "image_path": case.image_path,
            "enhanced_image_path": case.enhanced_image_path
        },
        "prediction": pred.prediction,
        "fracture_probability": pred.fracture_probability,
        "confidence": pred.confidence,
        "priority": pred.priority,
        "model": pred.model_name,
        "model_version": pred.model_version,
        "demo_mode": is_demo,
        "demo_notice": "DEMO PREDICTION — NOT GENERATED BY THE TRAINED CLINICAL MODEL." if is_demo else None,
        "gradcam_path": pred.gradcam_path,
        "gradcam_available": bool(pred.gradcam_path and os.path.exists(pred.gradcam_path)),
        "image_quality_score": case.image_quality_score,
        "image_quality_status": case.image_quality_status,
        "clinical_review_required": True,
        "disclaimer": "AI-assisted screening only. Final interpretation and clinical decision must be made by a qualified healthcare professional."
    }

@router.get("/gradcam/{case_id}")
def get_gradcam_info(case_id: str, db: Session = Depends(get_db)):
    pred = db.query(AIPrediction).filter(AIPrediction.case_id == case_id).first()
    if not pred or not pred.gradcam_path or not os.path.exists(pred.gradcam_path):
        raise HTTPException(status_code=404, detail="Grad-CAM visualization not available for this case")
    return {
        "case_id": case_id,
        "gradcam_path": pred.gradcam_path,
        "available": True,
        "explanation": "Grad-CAM highlights image regions that influenced the model prediction. It is an AI explanation and should not be interpreted as a confirmed fracture location."
    }

