import React, { useEffect, useState } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { FileCheck2, Activity, Flame, Stethoscope, Bot, RefreshCw, CheckCircle2, ShieldAlert, Cpu, AlertCircle } from 'lucide-react';
import { caseAPI, aiAPI, reviewAPI } from '../services/api';
import PriorityBadge from '../components/PriorityBadge';
import GradCAMViewer from '../components/GradCAMViewer';
import ImageComparisonViewer from '../components/ImageComparisonViewer';
import DisclaimerBanner from '../components/DisclaimerBanner';
import AIAssistantWidget from '../components/AIAssistantWidget';

const AIAnalysisResultPage = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const caseId = searchParams.get('case_id') || 'RF-2026-0001';

  const [caseData, setCaseData] = useState(null);
  const [result, setResult] = useState(null);
  const [reviewStatus, setReviewStatus] = useState('CONFIRMED_FRACTURE');
  const [reviewerNotes, setReviewerNotes] = useState('');
  const [reviewSaved, setReviewSaved] = useState(false);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState(null);

  useEffect(() => {
    fetchResultData();
  }, [caseId]);

  const fetchResultData = async () => {
    try {
      setLoading(true);
      setErrorMessage(null);
      const [caseRes, aiRes] = await Promise.all([
        caseAPI.get(caseId),
        aiAPI.getResult(caseId),
      ]);
      setCaseData(caseRes.data);
      setResult(aiRes.data);
      if (caseRes.data?.review) {
        setReviewStatus(caseRes.data.review.review_status || 'CONFIRMED_FRACTURE');
        setReviewerNotes(caseRes.data.review.reviewer_notes || '');
      }
    } catch (err) {
      console.error('Failed to load result data:', err);
      setErrorMessage('Failed to load AI screening result for this case.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveReview = async () => {
    try {
      await reviewAPI.submit({
        case_id: caseId,
        review_status: reviewStatus,
        reviewer_notes: reviewerNotes,
      });
      setReviewSaved(true);
      setTimeout(() => setReviewSaved(false), 3000);
    } catch (err) {
      console.error('Failed to submit review:', err);
    }
  };

  const patient = result?.patient || caseData?.patient || {
    patient_id: 'RF-PAT-001',
    name: 'Aarav Sharma',
    age: 42,
    gender: 'Male',
    hospital_name: 'Primary Rural Clinic',
  };

  const cInfo = result?.case || caseData?.case || {
    case_id: caseId,
    body_region: 'Wrist',
    image_quality_score: 91.0,
    image_quality_status: 'ACCEPTABLE',
    image_path: `uploads/original/${caseId}.jpg`,
    enhanced_image_path: `uploads/enhanced/${caseId}_enhanced.png`,
  };

  const resInfo = result || {
    prediction: 'Possible Fracture',
    fracture_probability: 0.87,
    confidence: 0.87,
    image_quality_score: 91.0,
    image_quality_status: 'ACCEPTABLE',
    priority: 'HIGH',
    model: 'EfficientNet-B0',
    model_version: 'v1.0',
    demo_mode: true,
    gradcam_path: `uploads/gradcam/gradcam_${caseId}.jpg`,
    gradcam_available: true,
  };

  const isDemoMode = resInfo.demo_mode ?? true;
  const isPoorQuality = cInfo.image_quality_status === 'POOR IMAGE QUALITY' || (cInfo.image_quality_score && cInfo.image_quality_score < 50.0);

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
            <FileCheck2 className="w-6 h-6 text-cyan-400" />
            AI Fracture Screening Results & Clinical Sign-Off
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Deep Learning EfficientNet-B0 prediction output, priority triage score, and Grad-CAM explainability map
          </p>
        </div>

        <span className="font-mono text-sm font-bold text-cyan-300 bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-xl">
          Case ID: {caseId}
        </span>
      </div>

      <DisclaimerBanner />

      {/* Demo Mode / Real Model Notice */}
      <div className={`p-3.5 rounded-xl border text-xs flex items-center justify-between gap-3 ${
        isDemoMode
          ? 'bg-amber-950/20 border-amber-500/40 text-amber-200'
          : 'bg-emerald-950/20 border-emerald-500/40 text-emerald-200'
      }`}>
        <div className="flex items-center gap-2.5">
          <Cpu className="w-4 h-4 shrink-0 text-amber-400" />
          <span className="font-bold">
            {isDemoMode ? (
              'DEMO PREDICTION — NOT GENERATED BY THE TRAINED CLINICAL MODEL.'
            ) : (
              'REAL CLINICAL MODEL INFERENCE — Powered by EfficientNet-B0 architecture checkpoint.'
            )}
          </span>
        </div>

        <button
          onClick={fetchResultData}
          className="text-slate-400 hover:text-slate-200 text-xs flex items-center gap-1"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          <span>Refresh</span>
        </button>
      </div>

      {/* Poor Quality Guardrail Warning Banner */}
      {isPoorQuality && (
        <div className="bg-rose-950/30 border border-rose-500/60 p-5 rounded-2xl space-y-2 text-xs text-rose-200">
          <div className="flex items-center gap-2 text-rose-300 font-extrabold text-sm">
            <AlertCircle className="w-5 h-5 text-rose-400" />
            <span>POOR IMAGE QUALITY WARNING</span>
          </div>
          <p>
            The uploaded X-ray image failed minimum radiographical quality standards (Score: {cInfo.image_quality_score || 0}%). 
            AI fracture screening results should be disregarded. Please upload a higher resolution, properly exposed X-ray.
          </p>
          <button
            onClick={() => navigate('/new-case')}
            className="mt-2 px-4 py-2 bg-rose-600 hover:bg-rose-500 text-white font-bold rounded-xl text-xs flex items-center gap-1.5"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>Re-upload Clearer X-ray</span>
          </button>
        </div>
      )}

      {/* Patient / Case Information Header Card */}
      <div className="glass-panel p-5 rounded-2xl border border-slate-800 grid grid-cols-2 md:grid-cols-5 gap-4 text-xs">
        <div>
          <span className="text-slate-400 block text-[10px] uppercase font-bold">Patient ID</span>
          <span className="font-bold text-slate-100 font-mono text-sm">{patient.patient_id}</span>
        </div>
        <div>
          <span className="text-slate-400 block text-[10px] uppercase font-bold">Patient Name</span>
          <span className="font-bold text-slate-100 text-xs">{patient.name}</span>
        </div>
        <div>
          <span className="text-slate-400 block text-[10px] uppercase font-bold">Age & Gender</span>
          <span className="font-semibold text-slate-200">{patient.age} Yrs / {patient.gender}</span>
        </div>
        <div>
          <span className="text-slate-400 block text-[10px] uppercase font-bold">Hospital Facility</span>
          <span className="font-semibold text-slate-200">{patient.hospital_name}</span>
        </div>
        <div>
          <span className="text-slate-400 block text-[10px] uppercase font-bold">Anatomical Region</span>
          <span className="font-bold text-teal-300 uppercase">{cInfo.body_region}</span>
        </div>
      </div>

      {/* AI Screening Summary Card */}
      <div className="glass-panel p-6 rounded-2xl border border-cyan-500/30 glow-cyan space-y-4">
        
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-4">
          <div>
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">AI Screening Result</span>
            <div className="text-2xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-teal-300 to-emerald-400 mt-0.5">
              AI Screening Result: {resInfo.prediction}
            </div>
          </div>

          <PriorityBadge priority={resInfo.priority} showDescription />
        </div>

        {/* Metric Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
          
          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
            <span className="text-slate-400 block text-[11px]">Model Confidence</span>
            <div className="text-xl font-extrabold text-cyan-300">{Math.round(resInfo.confidence * 100)}%</div>
            <span className="text-[10px] text-slate-500">Classification probability</span>
          </div>

          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
            <span className="text-slate-400 block text-[11px]">Image Quality Score</span>
            <div className="text-xl font-extrabold text-emerald-400">{cInfo.image_quality_score || 91}%</div>
            <span className="text-[10px] text-emerald-300 font-semibold">{cInfo.image_quality_status || 'ACCEPTABLE'}</span>
          </div>

          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
            <span className="text-slate-400 block text-[11px]">Model Architecture</span>
            <div className="text-sm font-bold text-slate-100">{resInfo.model}</div>
            <span className="text-[10px] text-slate-400">{resInfo.model_version || 'v1.0'}</span>
          </div>

          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
            <span className="text-slate-400 block text-[11px]">Clinical Review Status</span>
            <div className="text-xs font-bold text-amber-300">Required</div>
            <span className="text-[10px] text-slate-400">Professional sign-off needed</span>
          </div>

        </div>
      </div>

      {/* Grad-CAM Explainable AI Viewer */}
      <GradCAMViewer
        originalUrl={cInfo.image_path}
        enhancedUrl={cInfo.enhanced_image_path}
        gradcamUrl={resInfo.gradcam_path}
      />

      {/* Interactive OpenCV Image Comparison */}
      <ImageComparisonViewer
        originalUrl={cInfo.image_path}
        enhancedUrl={cInfo.enhanced_image_path}
      />

      {/* Clinical Review & Notes Form */}
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-4">
        
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <h3 className="text-base font-bold text-slate-100 flex items-center gap-2">
            <Stethoscope className="w-5 h-5 text-teal-400" />
            Professional Clinical Review Portal
          </h3>
          {reviewSaved && (
            <span className="text-xs text-emerald-400 font-bold flex items-center gap-1 bg-emerald-500/10 px-3 py-1 rounded-full border border-emerald-500/30">
              <CheckCircle2 className="w-3.5 h-3.5" /> Clinical review saved!
            </span>
          )}
        </div>

        <div className="space-y-4 text-xs">
          
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">Doctor / Radiologist Review Status</label>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              <button
                type="button"
                onClick={() => setReviewStatus('CONFIRMED_FRACTURE')}
                className={`p-3 rounded-xl border text-left transition-all ${
                  reviewStatus === 'CONFIRMED_FRACTURE'
                    ? 'bg-rose-500/20 border-rose-500 text-rose-300 font-bold'
                    : 'bg-slate-950 border-slate-800 text-slate-400'
                }`}
              >
                Confirmed Fracture
              </button>
              <button
                type="button"
                onClick={() => setReviewStatus('CONFIRMED_NO_FRACTURE')}
                className={`p-3 rounded-xl border text-left transition-all ${
                  reviewStatus === 'CONFIRMED_NO_FRACTURE'
                    ? 'bg-emerald-500/20 border-emerald-500 text-emerald-300 font-bold'
                    : 'bg-slate-950 border-slate-800 text-slate-400'
                }`}
              >
                Confirmed No Fracture
              </button>
              <button
                type="button"
                onClick={() => setReviewStatus('NEEDS_RETAKE')}
                className={`p-3 rounded-xl border text-left transition-all ${
                  reviewStatus === 'NEEDS_RETAKE'
                    ? 'bg-amber-500/20 border-amber-500 text-amber-300 font-bold'
                    : 'bg-slate-950 border-slate-800 text-slate-400'
                }`}
              >
                Needs X-ray Retake
              </button>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">Clinical Reviewer Notes & Remarks</label>
            <textarea
              rows="3"
              value={reviewerNotes}
              onChange={(e) => setReviewerNotes(e.target.value)}
              placeholder="Enter professional clinical findings, fracture type, or recommendation for orthopedic referral..."
              className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-xs text-slate-100 focus:outline-none focus:border-cyan-500"
            ></textarea>
          </div>

          <div className="flex justify-end pt-2">
            <button
              onClick={handleSaveReview}
              className="px-6 py-2.5 bg-gradient-to-r from-teal-500 to-emerald-500 text-slate-950 font-bold rounded-xl text-xs shadow-lg hover:opacity-95 transition-all"
            >
              Mark Case as Reviewed & Save Clinical Record
            </button>
          </div>

        </div>
      </div>

      {/* Context-aware Floating AI Assistant */}
      <AIAssistantWidget currentCaseId={caseId} currentPage="/results" />

    </div>
  );
};

export default AIAnalysisResultPage;
