import React, { useState } from 'react';
import { Settings, Sparkles, Key, Cpu, ShieldCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import DisclaimerBanner from '../components/DisclaimerBanner';

const SettingsPage = () => {
  const { demoMode, setDemoMode } = useAuth();
  const [provider, setProvider] = useState('mock');
  const [modelName, setModelName] = useState('gpt-4o-mini');
  const [apiKey, setApiKey] = useState('');
  const [saved, setSaved] = useState(false);

  const handleSave = (e) => {
    e.preventDefault();
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      
      <div>
        <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
          <Settings className="w-6 h-6 text-cyan-400" />
          System Settings & AI Provider Configuration
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Configure DEMO vs REAL PyTorch model mode, modular LLM AI provider architecture, and API credentials
        </p>
      </div>

      <DisclaimerBanner />

      {/* Mode Control Card (Item 34) */}
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-4">
        <h3 className="text-base font-bold text-slate-100 flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-cyan-400" />
          Screening Execution Mode
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          
          <div
            onClick={() => setDemoMode(true)}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              demoMode
                ? 'bg-cyan-500/20 border-cyan-500 text-cyan-200 glow-cyan'
                : 'bg-slate-950 border-slate-800 text-slate-400 hover:border-slate-700'
            }`}
          >
            <div className="font-bold text-sm text-cyan-300">DEMO MODE</div>
            <p className="mt-1 text-[11px] leading-relaxed">
              Uses simulated clinical dataset responses for fast offline demonstrations. Displays "DEMO PREDICTION — NOT GENERATED BY TRAINED CLINICAL MODEL".
            </p>
          </div>

          <div
            onClick={() => setDemoMode(false)}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              !demoMode
                ? 'bg-emerald-500/20 border-emerald-500 text-emerald-200 glow-emerald'
                : 'bg-slate-950 border-slate-800 text-slate-400 hover:border-slate-700'
            }`}
          >
            <div className="font-bold text-sm text-emerald-300">REAL MODEL MODE</div>
            <p className="mt-1 text-[11px] leading-relaxed">
              Executes live PyTorch EfficientNet-B0 forward pass and computes actual Grad-CAM backprop feature maps.
            </p>
          </div>

        </div>
      </div>

      {/* Modular AI Assistant Provider Config (Item 32) */}
      <form onSubmit={handleSave} className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-5 text-xs">
        
        <div className="border-b border-slate-800 pb-3">
          <h3 className="text-base font-bold text-slate-100 flex items-center gap-2">
            <Cpu className="w-5 h-5 text-teal-400" />
            AI Assistant Modular Provider System
          </h3>
          <p className="text-slate-400 mt-1">
            Configure conversational LLM backend. Supports built-in offline smart mock provider, OpenAI, or local LLM endpoints.
          </p>
        </div>

        <div>
          <label className="block font-semibold text-slate-300 mb-1">AI Assistant Provider Architecture</label>
          <select
            value={provider}
            onChange={(e) => setProvider(e.target.value)}
            className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 focus:outline-none focus:border-cyan-500"
          >
            <option value="mock">Built-in Smart Mock Provider (Offline & DB Querying - Recommended)</option>
            <option value="openai">OpenAI GPT Provider (Requires OpenAI API Key)</option>
            <option value="local">Local LLM / Ollama Provider</option>
          </select>
        </div>

        {provider === 'openai' && (
          <div className="space-y-3 pt-2">
            <div>
              <label className="block font-semibold text-slate-300 mb-1">OpenAI Model Target</label>
              <input
                type="text"
                value={modelName}
                onChange={(e) => setModelName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 font-mono"
              />
            </div>

            <div>
              <label className="block font-semibold text-slate-300 mb-1">OpenAI Secret API Key</label>
              <div className="relative">
                <Key className="w-4 h-4 text-slate-500 absolute left-3 top-2.5" />
                <input
                  type="password"
                  placeholder="sk-..."
                  value={apiKey}
                  onChange={(e) => setApiKey(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-9 pr-3 py-2 text-slate-100 font-mono"
                />
              </div>
              <p className="text-[10px] text-slate-500 mt-1">
                🔒 API keys are stored securely in backend environment variables and never exposed to the frontend.
              </p>
            </div>
          </div>
        )}

        <div className="flex justify-between items-center pt-3 border-t border-slate-800">
          {saved && <span className="text-emerald-400 font-bold">Settings saved successfully!</span>}
          <button
            type="submit"
            className="ml-auto px-6 py-2.5 bg-gradient-to-r from-cyan-500 to-teal-500 text-slate-950 font-bold rounded-xl shadow-lg glow-cyan hover:opacity-95 transition-all"
          >
            Save Settings
          </button>
        </div>

      </form>

    </div>
  );
};

export default SettingsPage;
